sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 998712
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: web-penguin
    access-key-id: LTAI5tBhC1WpM9eTyYHsU55k
    access-key-secret: gBwCnMmJUHo3QgC5hJWGuHrSEguBZV
  redis:
    host: localhost
    port: 6379
    database: 9
  wechat:
    appid: wxeebaa1a5211824c5
    secret: c76d64b40a06456af2448c1752f45b37